"""empty message

Revision ID: 16f3806031c1
Revises: c52ae5c8a673
Create Date: 2020-06-08 19:30:24.964655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16f3806031c1'
down_revision = 'c52ae5c8a673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'city')
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'facebook_link')
    op.drop_column('artist', 'name')
    op.drop_column('artist', 'seeking_venues')
    op.drop_column('artist', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('seeking_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
