"""empty message

Revision ID: 82675f25f7f7
Revises: 73680c8693c3
Create Date: 2020-06-05 19:26:38.557718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82675f25f7f7'
down_revision = '73680c8693c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
